# Generated by Django 5.1.4 on 2025-01-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, upload_to='photos/', verbose_name='изображение')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['views'],
            },
        ),
    ]
