# Generated by Django 5.1.4 on 2025-01-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['date_created'], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
